require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'valkyrie-dynamodb.gemspec'
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'
    - 'lib/valkyrie/specs/**/*'
    - 'lib/specs/**/*'
    - 'lib/tasks/dev.rake'
Metrics/MethodLength:
  Max: 15
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: true
  Exclude:
    - 'spec/support/null_adapter.rb'
Security/MarshalLoad:
  Enabled: true
  Exclude:
    - 'lib/valkyrie/persistence/dynamodb/query_service.rb'
